# Generated by Django 4.2.6 on 2025-03-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
    ]
