# Generated by Django 4.2.6 on 2025-03-11 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productionorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量'),
        ),
    ]
