# Generated by Django 5.1.7 on 2025-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_productionorder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=100, verbose_name='季节'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=100, verbose_name='系列'),
        ),
    ]
